### PR TITLE
Update to 0.8.1

### PR DESCRIPTION
**Pull request by hfiguiere**
- and drumstick 2.1.0

### CODE REVIEW

**Comment by pedrolcl** [comment]
I can't test it:

~~~
$ flatpak install --user https://dl.flathub.org/build-repo/40782/net.sourceforge.VMPK.flatpakref
error: Invalid .flatpakref: Key file contains line “<html>” which is not a key-value pair, group, or comment

$ wget https://dl.flathub.org/build-repo/40782/net.sourceforge.VMPK.flatpakref
--2021-03-27 16:39:39--  https://dl.flathub.org/build-repo/net.sourceforge.VMPK.flatpakref
Resolving dl.flathub.org (dl.flathub.org)... 151.101.134.217, 2a04:4e42:1f::729
Connecting to dl.flathub.org (dl.flathub.org)|151.101.134.217|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2021-03-27 16:39:39 ERROR 404: Not Found.
~~~

**Comment by hfiguiere** [comment]
Sorry the build expired.

I was meaning to test and merge and got sidetracked.

Will start a new build.

**Comment by hfiguiere** [comment]
bot, build

**Comment by pedrolcl** [comment]
Thanks! this time I've tested correctly. I can merge if you want.

**Comment by hfiguiere** [comment]
I can merge too, just that I got sidetracked testing (didn't have headphones, and then somewhat forgot).

Thanks!

**Pull request merged**
